services:
  db:
    image: postgres:16-alpine
    container_name: ev-scheduler-db
    environment:
      POSTGRES_USER: ev_user
      POSTGRES_PASSWORD: ev_pass
      POSTGRES_DB: ev_scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
